#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate --run-syncdb
gunicorn -w 2 -b 0.0.0.0:8001 music_site.wsgi:application --timeout 120 --worker-class=gevent
#python manage.py runserver 0.0.0.0:8001