// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/proto/download_source.proto

package tagplugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DownloadSource_Search_FullMethodName        = "/tagplugin.DownloadSource/Search"
	DownloadSource_Download_FullMethodName      = "/tagplugin.DownloadSource/Download"
	DownloadSource_GetPluginInfo_FullMethodName = "/tagplugin.DownloadSource/GetPluginInfo"
)

// DownloadSourceClient is the client API for DownloadSource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DownloadSource handles search + download from platforms like YouTube.
type DownloadSourceClient interface {
	Search(ctx context.Context, in *DownloadSearchRequest, opts ...grpc.CallOption) (*DownloadSearchResponse, error)
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error)
	GetPluginInfo(ctx context.Context, in *DownloadPluginInfoRequest, opts ...grpc.CallOption) (*DownloadPluginInfoResponse, error)
}

type downloadSourceClient struct {
	cc grpc.ClientConnInterface
}

func NewDownloadSourceClient(cc grpc.ClientConnInterface) DownloadSourceClient {
	return &downloadSourceClient{cc}
}

func (c *downloadSourceClient) Search(ctx context.Context, in *DownloadSearchRequest, opts ...grpc.CallOption) (*DownloadSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadSearchResponse)
	err := c.cc.Invoke(ctx, DownloadSource_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadSourceClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadResponse)
	err := c.cc.Invoke(ctx, DownloadSource_Download_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadSourceClient) GetPluginInfo(ctx context.Context, in *DownloadPluginInfoRequest, opts ...grpc.CallOption) (*DownloadPluginInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadPluginInfoResponse)
	err := c.cc.Invoke(ctx, DownloadSource_GetPluginInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DownloadSourceServer is the server API for DownloadSource service.
// All implementations must embed UnimplementedDownloadSourceServer
// for forward compatibility.
//
// DownloadSource handles search + download from platforms like YouTube.
type DownloadSourceServer interface {
	Search(context.Context, *DownloadSearchRequest) (*DownloadSearchResponse, error)
	Download(context.Context, *DownloadRequest) (*DownloadResponse, error)
	GetPluginInfo(context.Context, *DownloadPluginInfoRequest) (*DownloadPluginInfoResponse, error)
	mustEmbedUnimplementedDownloadSourceServer()
}

// UnimplementedDownloadSourceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDownloadSourceServer struct{}

func (UnimplementedDownloadSourceServer) Search(context.Context, *DownloadSearchRequest) (*DownloadSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedDownloadSourceServer) Download(context.Context, *DownloadRequest) (*DownloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedDownloadSourceServer) GetPluginInfo(context.Context, *DownloadPluginInfoRequest) (*DownloadPluginInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPluginInfo not implemented")
}
func (UnimplementedDownloadSourceServer) mustEmbedUnimplementedDownloadSourceServer() {}
func (UnimplementedDownloadSourceServer) testEmbeddedByValue()                        {}

// UnsafeDownloadSourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DownloadSourceServer will
// result in compilation errors.
type UnsafeDownloadSourceServer interface {
	mustEmbedUnimplementedDownloadSourceServer()
}

func RegisterDownloadSourceServer(s grpc.ServiceRegistrar, srv DownloadSourceServer) {
	// If the following call panics, it indicates UnimplementedDownloadSourceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DownloadSource_ServiceDesc, srv)
}

func _DownloadSource_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadSourceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DownloadSource_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadSourceServer).Search(ctx, req.(*DownloadSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DownloadSource_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadSourceServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DownloadSource_Download_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadSourceServer).Download(ctx, req.(*DownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DownloadSource_GetPluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadPluginInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadSourceServer).GetPluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DownloadSource_GetPluginInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadSourceServer).GetPluginInfo(ctx, req.(*DownloadPluginInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DownloadSource_ServiceDesc is the grpc.ServiceDesc for DownloadSource service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DownloadSource_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tagplugin.DownloadSource",
	HandlerType: (*DownloadSourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _DownloadSource_Search_Handler,
		},
		{
			MethodName: "Download",
			Handler:    _DownloadSource_Download_Handler,
		},
		{
			MethodName: "GetPluginInfo",
			Handler:    _DownloadSource_GetPluginInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/download_source.proto",
}
