// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/tag_source.proto

package tagplugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Song is the normalized music-metadata record returned by every tag source.
type Song struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Artist        string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	ArtistId      string                 `protobuf:"bytes,4,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	Album         string                 `protobuf:"bytes,5,opt,name=album,proto3" json:"album,omitempty"`
	AlbumId       string                 `protobuf:"bytes,6,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	AlbumImg      string                 `protobuf:"bytes,7,opt,name=album_img,json=albumImg,proto3" json:"album_img,omitempty"`
	Year          string                 `protobuf:"bytes,8,opt,name=year,proto3" json:"year,omitempty"`
	Source        string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"` // populated by gateway handler, not the plugin itself
	Genre         string                 `protobuf:"bytes,10,opt,name=genre,proto3" json:"genre,omitempty"`
	Mid           string                 `protobuf:"bytes,11,opt,name=mid,proto3" json:"mid,omitempty"`
	Cover         string                 `protobuf:"bytes,12,opt,name=cover,proto3" json:"cover,omitempty"`
	Score         float64                `protobuf:"fixed64,13,opt,name=score,proto3" json:"score,omitempty"` // populated by smart_tag aggregation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Song) Reset() {
	*x = Song{}
	mi := &file_api_proto_tag_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Song) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Song) ProtoMessage() {}

func (x *Song) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tag_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Song.ProtoReflect.Descriptor instead.
func (*Song) Descriptor() ([]byte, []int) {
	return file_api_proto_tag_source_proto_rawDescGZIP(), []int{0}
}

func (x *Song) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Song) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Song) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Song) GetArtistId() string {
	if x != nil {
		return x.ArtistId
	}
	return ""
}

func (x *Song) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *Song) GetAlbumId() string {
	if x != nil {
		return x.AlbumId
	}
	return ""
}

func (x *Song) GetAlbumImg() string {
	if x != nil {
		return x.AlbumImg
	}
	return ""
}

func (x *Song) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *Song) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Song) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *Song) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *Song) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Song) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"` // 1-indexed
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_proto_tag_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tag_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tag_source_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*Song                `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_proto_tag_source_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tag_source_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tag_source_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetSongs() []*Song {
	if x != nil {
		return x.Songs
	}
	return nil
}

func (x *SearchResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type FetchId3Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchId3Request) Reset() {
	*x = FetchId3Request{}
	mi := &file_api_proto_tag_source_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchId3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchId3Request) ProtoMessage() {}

func (x *FetchId3Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tag_source_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchId3Request.ProtoReflect.Descriptor instead.
func (*FetchId3Request) Descriptor() ([]byte, []int) {
	return file_api_proto_tag_source_proto_rawDescGZIP(), []int{3}
}

func (x *FetchId3Request) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type FetchId3Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*Song                `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchId3Response) Reset() {
	*x = FetchId3Response{}
	mi := &file_api_proto_tag_source_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchId3Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchId3Response) ProtoMessage() {}

func (x *FetchId3Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tag_source_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchId3Response.ProtoReflect.Descriptor instead.
func (*FetchId3Response) Descriptor() ([]byte, []int) {
	return file_api_proto_tag_source_proto_rawDescGZIP(), []int{4}
}

func (x *FetchId3Response) GetSongs() []*Song {
	if x != nil {
		return x.Songs
	}
	return nil
}

type FetchLyricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SongId        string                 `protobuf:"bytes,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchLyricRequest) Reset() {
	*x = FetchLyricRequest{}
	mi := &file_api_proto_tag_source_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchLyricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLyricRequest) ProtoMessage() {}

func (x *FetchLyricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tag_source_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLyricRequest.ProtoReflect.Descriptor instead.
func (*FetchLyricRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tag_source_proto_rawDescGZIP(), []int{5}
}

func (x *FetchLyricRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

type FetchLyricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lyric         string                 `protobuf:"bytes,1,opt,name=lyric,proto3" json:"lyric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchLyricResponse) Reset() {
	*x = FetchLyricResponse{}
	mi := &file_api_proto_tag_source_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchLyricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLyricResponse) ProtoMessage() {}

func (x *FetchLyricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tag_source_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLyricResponse.ProtoReflect.Descriptor instead.
func (*FetchLyricResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tag_source_proto_rawDescGZIP(), []int{6}
}

func (x *FetchLyricResponse) GetLyric() string {
	if x != nil {
		return x.Lyric
	}
	return ""
}

type PluginInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfoRequest) Reset() {
	*x = PluginInfoRequest{}
	mi := &file_api_proto_tag_source_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfoRequest) ProtoMessage() {}

func (x *PluginInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tag_source_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfoRequest.ProtoReflect.Descriptor instead.
func (*PluginInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tag_source_proto_rawDescGZIP(), []int{7}
}

type PluginInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName    string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	SupportsSearch bool                   `protobuf:"varint,3,opt,name=supports_search,json=supportsSearch,proto3" json:"supports_search,omitempty"`
	SupportsLyric  bool                   `protobuf:"varint,4,opt,name=supports_lyric,json=supportsLyric,proto3" json:"supports_lyric,omitempty"`
	SupportsId3    bool                   `protobuf:"varint,5,opt,name=supports_id3,json=supportsId3,proto3" json:"supports_id3,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PluginInfoResponse) Reset() {
	*x = PluginInfoResponse{}
	mi := &file_api_proto_tag_source_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfoResponse) ProtoMessage() {}

func (x *PluginInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tag_source_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfoResponse.ProtoReflect.Descriptor instead.
func (*PluginInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tag_source_proto_rawDescGZIP(), []int{8}
}

func (x *PluginInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfoResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PluginInfoResponse) GetSupportsSearch() bool {
	if x != nil {
		return x.SupportsSearch
	}
	return false
}

func (x *PluginInfoResponse) GetSupportsLyric() bool {
	if x != nil {
		return x.SupportsLyric
	}
	return false
}

func (x *PluginInfoResponse) GetSupportsId3() bool {
	if x != nil {
		return x.SupportsId3
	}
	return false
}

var File_api_proto_tag_source_proto protoreflect.FileDescriptor

const file_api_proto_tag_source_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/tag_source.proto\x12\ttagplugin\"\xad\x02\n" +
	"\x04Song\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x1b\n" +
	"\tartist_id\x18\x04 \x01(\tR\bartistId\x12\x14\n" +
	"\x05album\x18\x05 \x01(\tR\x05album\x12\x19\n" +
	"\balbum_id\x18\x06 \x01(\tR\aalbumId\x12\x1b\n" +
	"\talbum_img\x18\a \x01(\tR\balbumImg\x12\x12\n" +
	"\x04year\x18\b \x01(\tR\x04year\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x12\x14\n" +
	"\x05genre\x18\n" +
	" \x01(\tR\x05genre\x12\x10\n" +
	"\x03mid\x18\v \x01(\tR\x03mid\x12\x14\n" +
	"\x05cover\x18\f \x01(\tR\x05cover\x12\x14\n" +
	"\x05score\x18\r \x01(\x01R\x05score\"O\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"R\n" +
	"\x0eSearchResponse\x12%\n" +
	"\x05songs\x18\x01 \x03(\v2\x0f.tagplugin.SongR\x05songs\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"'\n" +
	"\x0fFetchId3Request\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"9\n" +
	"\x10FetchId3Response\x12%\n" +
	"\x05songs\x18\x01 \x03(\v2\x0f.tagplugin.SongR\x05songs\",\n" +
	"\x11FetchLyricRequest\x12\x17\n" +
	"\asong_id\x18\x01 \x01(\tR\x06songId\"*\n" +
	"\x12FetchLyricResponse\x12\x14\n" +
	"\x05lyric\x18\x01 \x01(\tR\x05lyric\"\x13\n" +
	"\x11PluginInfoRequest\"\xbe\x01\n" +
	"\x12PluginInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12'\n" +
	"\x0fsupports_search\x18\x03 \x01(\bR\x0esupportsSearch\x12%\n" +
	"\x0esupports_lyric\x18\x04 \x01(\bR\rsupportsLyric\x12!\n" +
	"\fsupports_id3\x18\x05 \x01(\bR\vsupportsId32\xaf\x02\n" +
	"\tTagSource\x12L\n" +
	"\rGetPluginInfo\x12\x1c.tagplugin.PluginInfoRequest\x1a\x1d.tagplugin.PluginInfoResponse\x12=\n" +
	"\x06Search\x12\x18.tagplugin.SearchRequest\x1a\x19.tagplugin.SearchResponse\x12J\n" +
	"\x0fFetchId3ByTitle\x12\x1a.tagplugin.FetchId3Request\x1a\x1b.tagplugin.FetchId3Response\x12I\n" +
	"\n" +
	"FetchLyric\x12\x1c.tagplugin.FetchLyricRequest\x1a\x1d.tagplugin.FetchLyricResponseB\"Z go-music-tag/api/proto/tagpluginb\x06proto3"

var (
	file_api_proto_tag_source_proto_rawDescOnce sync.Once
	file_api_proto_tag_source_proto_rawDescData []byte
)

func file_api_proto_tag_source_proto_rawDescGZIP() []byte {
	file_api_proto_tag_source_proto_rawDescOnce.Do(func() {
		file_api_proto_tag_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_tag_source_proto_rawDesc), len(file_api_proto_tag_source_proto_rawDesc)))
	})
	return file_api_proto_tag_source_proto_rawDescData
}

var file_api_proto_tag_source_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_tag_source_proto_goTypes = []any{
	(*Song)(nil),               // 0: tagplugin.Song
	(*SearchRequest)(nil),      // 1: tagplugin.SearchRequest
	(*SearchResponse)(nil),     // 2: tagplugin.SearchResponse
	(*FetchId3Request)(nil),    // 3: tagplugin.FetchId3Request
	(*FetchId3Response)(nil),   // 4: tagplugin.FetchId3Response
	(*FetchLyricRequest)(nil),  // 5: tagplugin.FetchLyricRequest
	(*FetchLyricResponse)(nil), // 6: tagplugin.FetchLyricResponse
	(*PluginInfoRequest)(nil),  // 7: tagplugin.PluginInfoRequest
	(*PluginInfoResponse)(nil), // 8: tagplugin.PluginInfoResponse
}
var file_api_proto_tag_source_proto_depIdxs = []int32{
	0, // 0: tagplugin.SearchResponse.songs:type_name -> tagplugin.Song
	0, // 1: tagplugin.FetchId3Response.songs:type_name -> tagplugin.Song
	7, // 2: tagplugin.TagSource.GetPluginInfo:input_type -> tagplugin.PluginInfoRequest
	1, // 3: tagplugin.TagSource.Search:input_type -> tagplugin.SearchRequest
	3, // 4: tagplugin.TagSource.FetchId3ByTitle:input_type -> tagplugin.FetchId3Request
	5, // 5: tagplugin.TagSource.FetchLyric:input_type -> tagplugin.FetchLyricRequest
	8, // 6: tagplugin.TagSource.GetPluginInfo:output_type -> tagplugin.PluginInfoResponse
	2, // 7: tagplugin.TagSource.Search:output_type -> tagplugin.SearchResponse
	4, // 8: tagplugin.TagSource.FetchId3ByTitle:output_type -> tagplugin.FetchId3Response
	6, // 9: tagplugin.TagSource.FetchLyric:output_type -> tagplugin.FetchLyricResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_tag_source_proto_init() }
func file_api_proto_tag_source_proto_init() {
	if File_api_proto_tag_source_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_tag_source_proto_rawDesc), len(file_api_proto_tag_source_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_tag_source_proto_goTypes,
		DependencyIndexes: file_api_proto_tag_source_proto_depIdxs,
		MessageInfos:      file_api_proto_tag_source_proto_msgTypes,
	}.Build()
	File_api_proto_tag_source_proto = out.File
	file_api_proto_tag_source_proto_goTypes = nil
	file_api_proto_tag_source_proto_depIdxs = nil
}
