// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/download_source.proto

package tagplugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	MaxResults    int32                  `protobuf:"varint,2,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadSearchRequest) Reset() {
	*x = DownloadSearchRequest{}
	mi := &file_api_proto_download_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSearchRequest) ProtoMessage() {}

func (x *DownloadSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_download_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSearchRequest.ProtoReflect.Descriptor instead.
func (*DownloadSearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_download_source_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *DownloadSearchRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type DownloadItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Duration      float64                `protobuf:"fixed64,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Channel       string                 `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,6,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadItem) Reset() {
	*x = DownloadItem{}
	mi := &file_api_proto_download_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadItem) ProtoMessage() {}

func (x *DownloadItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_download_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadItem.ProtoReflect.Descriptor instead.
func (*DownloadItem) Descriptor() ([]byte, []int) {
	return file_api_proto_download_source_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DownloadItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DownloadItem) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *DownloadItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DownloadItem) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *DownloadItem) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

type DownloadSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DownloadItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadSearchResponse) Reset() {
	*x = DownloadSearchResponse{}
	mi := &file_api_proto_download_source_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSearchResponse) ProtoMessage() {}

func (x *DownloadSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_download_source_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSearchResponse.ProtoReflect.Descriptor instead.
func (*DownloadSearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_download_source_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadSearchResponse) GetItems() []*DownloadItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	DownloadDir   string                 `protobuf:"bytes,2,opt,name=download_dir,json=downloadDir,proto3" json:"download_dir,omitempty"` // optional override
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_api_proto_download_source_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_download_source_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_download_source_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *DownloadRequest) GetDownloadDir() string {
	if x != nil {
		return x.DownloadDir
	}
	return ""
}

type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_api_proto_download_source_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_download_source_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_download_source_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DownloadResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *DownloadResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *DownloadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DownloadPluginInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadPluginInfoRequest) Reset() {
	*x = DownloadPluginInfoRequest{}
	mi := &file_api_proto_download_source_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadPluginInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadPluginInfoRequest) ProtoMessage() {}

func (x *DownloadPluginInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_download_source_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadPluginInfoRequest.ProtoReflect.Descriptor instead.
func (*DownloadPluginInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_download_source_proto_rawDescGZIP(), []int{5}
}

type DownloadPluginInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadPluginInfoResponse) Reset() {
	*x = DownloadPluginInfoResponse{}
	mi := &file_api_proto_download_source_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadPluginInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadPluginInfoResponse) ProtoMessage() {}

func (x *DownloadPluginInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_download_source_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadPluginInfoResponse.ProtoReflect.Descriptor instead.
func (*DownloadPluginInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_download_source_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadPluginInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DownloadPluginInfoResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_api_proto_download_source_proto protoreflect.FileDescriptor

const file_api_proto_download_source_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/download_source.proto\x12\ttagplugin\"N\n" +
	"\x15DownloadSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n" +
	"\vmax_results\x18\x02 \x01(\x05R\n" +
	"maxResults\"\x9a\x01\n" +
	"\fDownloadItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x01R\bduration\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x18\n" +
	"\achannel\x18\x05 \x01(\tR\achannel\x12\x1c\n" +
	"\tthumbnail\x18\x06 \x01(\tR\tthumbnail\"G\n" +
	"\x16DownloadSearchResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.tagplugin.DownloadItemR\x05items\"O\n" +
	"\x0fDownloadRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12!\n" +
	"\fdownload_dir\x18\x02 \x01(\tR\vdownloadDir\"|\n" +
	"\x10DownloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x1b\n" +
	"\x19DownloadPluginInfoRequest\"S\n" +
	"\x1aDownloadPluginInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName2\x82\x02\n" +
	"\x0eDownloadSource\x12M\n" +
	"\x06Search\x12 .tagplugin.DownloadSearchRequest\x1a!.tagplugin.DownloadSearchResponse\x12C\n" +
	"\bDownload\x12\x1a.tagplugin.DownloadRequest\x1a\x1b.tagplugin.DownloadResponse\x12\\\n" +
	"\rGetPluginInfo\x12$.tagplugin.DownloadPluginInfoRequest\x1a%.tagplugin.DownloadPluginInfoResponseB\"Z go-music-tag/api/proto/tagpluginb\x06proto3"

var (
	file_api_proto_download_source_proto_rawDescOnce sync.Once
	file_api_proto_download_source_proto_rawDescData []byte
)

func file_api_proto_download_source_proto_rawDescGZIP() []byte {
	file_api_proto_download_source_proto_rawDescOnce.Do(func() {
		file_api_proto_download_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_download_source_proto_rawDesc), len(file_api_proto_download_source_proto_rawDesc)))
	})
	return file_api_proto_download_source_proto_rawDescData
}

var file_api_proto_download_source_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_download_source_proto_goTypes = []any{
	(*DownloadSearchRequest)(nil),      // 0: tagplugin.DownloadSearchRequest
	(*DownloadItem)(nil),               // 1: tagplugin.DownloadItem
	(*DownloadSearchResponse)(nil),     // 2: tagplugin.DownloadSearchResponse
	(*DownloadRequest)(nil),            // 3: tagplugin.DownloadRequest
	(*DownloadResponse)(nil),           // 4: tagplugin.DownloadResponse
	(*DownloadPluginInfoRequest)(nil),  // 5: tagplugin.DownloadPluginInfoRequest
	(*DownloadPluginInfoResponse)(nil), // 6: tagplugin.DownloadPluginInfoResponse
}
var file_api_proto_download_source_proto_depIdxs = []int32{
	1, // 0: tagplugin.DownloadSearchResponse.items:type_name -> tagplugin.DownloadItem
	0, // 1: tagplugin.DownloadSource.Search:input_type -> tagplugin.DownloadSearchRequest
	3, // 2: tagplugin.DownloadSource.Download:input_type -> tagplugin.DownloadRequest
	5, // 3: tagplugin.DownloadSource.GetPluginInfo:input_type -> tagplugin.DownloadPluginInfoRequest
	2, // 4: tagplugin.DownloadSource.Search:output_type -> tagplugin.DownloadSearchResponse
	4, // 5: tagplugin.DownloadSource.Download:output_type -> tagplugin.DownloadResponse
	6, // 6: tagplugin.DownloadSource.GetPluginInfo:output_type -> tagplugin.DownloadPluginInfoResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_download_source_proto_init() }
func file_api_proto_download_source_proto_init() {
	if File_api_proto_download_source_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_download_source_proto_rawDesc), len(file_api_proto_download_source_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_download_source_proto_goTypes,
		DependencyIndexes: file_api_proto_download_source_proto_depIdxs,
		MessageInfos:      file_api_proto_download_source_proto_msgTypes,
	}.Build()
	File_api_proto_download_source_proto = out.File
	file_api_proto_download_source_proto_goTypes = nil
	file_api_proto_download_source_proto_depIdxs = nil
}
