// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/proto/tag_source.proto

package tagplugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TagSource_GetPluginInfo_FullMethodName   = "/tagplugin.TagSource/GetPluginInfo"
	TagSource_Search_FullMethodName          = "/tagplugin.TagSource/Search"
	TagSource_FetchId3ByTitle_FullMethodName = "/tagplugin.TagSource/FetchId3ByTitle"
	TagSource_FetchLyric_FullMethodName      = "/tagplugin.TagSource/FetchLyric"
)

// TagSourceClient is the client API for TagSource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TagSource handles metadata search + ID3 lookup + lyric fetch for a single
// music platform. One process can register many tag sources (each with its
// own gRPC server) and they all share this single interface.
type TagSourceClient interface {
	GetPluginInfo(ctx context.Context, in *PluginInfoRequest, opts ...grpc.CallOption) (*PluginInfoResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	FetchId3ByTitle(ctx context.Context, in *FetchId3Request, opts ...grpc.CallOption) (*FetchId3Response, error)
	FetchLyric(ctx context.Context, in *FetchLyricRequest, opts ...grpc.CallOption) (*FetchLyricResponse, error)
}

type tagSourceClient struct {
	cc grpc.ClientConnInterface
}

func NewTagSourceClient(cc grpc.ClientConnInterface) TagSourceClient {
	return &tagSourceClient{cc}
}

func (c *tagSourceClient) GetPluginInfo(ctx context.Context, in *PluginInfoRequest, opts ...grpc.CallOption) (*PluginInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfoResponse)
	err := c.cc.Invoke(ctx, TagSource_GetPluginInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagSourceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, TagSource_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagSourceClient) FetchId3ByTitle(ctx context.Context, in *FetchId3Request, opts ...grpc.CallOption) (*FetchId3Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchId3Response)
	err := c.cc.Invoke(ctx, TagSource_FetchId3ByTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagSourceClient) FetchLyric(ctx context.Context, in *FetchLyricRequest, opts ...grpc.CallOption) (*FetchLyricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchLyricResponse)
	err := c.cc.Invoke(ctx, TagSource_FetchLyric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TagSourceServer is the server API for TagSource service.
// All implementations must embed UnimplementedTagSourceServer
// for forward compatibility.
//
// TagSource handles metadata search + ID3 lookup + lyric fetch for a single
// music platform. One process can register many tag sources (each with its
// own gRPC server) and they all share this single interface.
type TagSourceServer interface {
	GetPluginInfo(context.Context, *PluginInfoRequest) (*PluginInfoResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	FetchId3ByTitle(context.Context, *FetchId3Request) (*FetchId3Response, error)
	FetchLyric(context.Context, *FetchLyricRequest) (*FetchLyricResponse, error)
	mustEmbedUnimplementedTagSourceServer()
}

// UnimplementedTagSourceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTagSourceServer struct{}

func (UnimplementedTagSourceServer) GetPluginInfo(context.Context, *PluginInfoRequest) (*PluginInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPluginInfo not implemented")
}
func (UnimplementedTagSourceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedTagSourceServer) FetchId3ByTitle(context.Context, *FetchId3Request) (*FetchId3Response, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchId3ByTitle not implemented")
}
func (UnimplementedTagSourceServer) FetchLyric(context.Context, *FetchLyricRequest) (*FetchLyricResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchLyric not implemented")
}
func (UnimplementedTagSourceServer) mustEmbedUnimplementedTagSourceServer() {}
func (UnimplementedTagSourceServer) testEmbeddedByValue()                   {}

// UnsafeTagSourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TagSourceServer will
// result in compilation errors.
type UnsafeTagSourceServer interface {
	mustEmbedUnimplementedTagSourceServer()
}

func RegisterTagSourceServer(s grpc.ServiceRegistrar, srv TagSourceServer) {
	// If the following call panics, it indicates UnimplementedTagSourceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TagSource_ServiceDesc, srv)
}

func _TagSource_GetPluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagSourceServer).GetPluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagSource_GetPluginInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagSourceServer).GetPluginInfo(ctx, req.(*PluginInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagSource_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagSourceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagSource_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagSourceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagSource_FetchId3ByTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchId3Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagSourceServer).FetchId3ByTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagSource_FetchId3ByTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagSourceServer).FetchId3ByTitle(ctx, req.(*FetchId3Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagSource_FetchLyric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchLyricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagSourceServer).FetchLyric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagSource_FetchLyric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagSourceServer).FetchLyric(ctx, req.(*FetchLyricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TagSource_ServiceDesc is the grpc.ServiceDesc for TagSource service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TagSource_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tagplugin.TagSource",
	HandlerType: (*TagSourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPluginInfo",
			Handler:    _TagSource_GetPluginInfo_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _TagSource_Search_Handler,
		},
		{
			MethodName: "FetchId3ByTitle",
			Handler:    _TagSource_FetchId3ByTitle_Handler,
		},
		{
			MethodName: "FetchLyric",
			Handler:    _TagSource_FetchLyric_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/tag_source.proto",
}
